services:
  app:
    container_name: indimed.lt
    build:
      dockerfile: Dockerfile
      args:
        WWWGROUP: 1000
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8080:8080
